name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-push-gcr:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install --force

      - name: Test
        run: npm run test

      - name: Configure Git
        run: |
          git config --global user.name 'Omar Abdelhadi'
          git config --global user.email 'omarabdelhadi@cmail.carleton.ca'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Deploy
        run: npm run deploy
